spring:
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: "jdbc:mysql://steninapp-server.mysql.database.azure.com:3306/steninapp-database?serverTimezone=UTC&sslmode=required&user=pcrgruerpz&password=Verisitas76"
    username: pcrgruerpz
    password: Verisitas76
  servlet:
    multipart:
      enabled: true
      max-file-size: 50MB
      max-request-size: 50MB
  mvc:
    hiddenmethod:
      filter:
        enabled: true
  sql:
    init:
      mode: always
  jpa:
    #Choose either MySQL 8 or MySQL 5 below
    # For MySQL 8
    database-platform: org.hibernate.dialect.MySQL8Dialect
    #For MySQL 5
    #database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
    defer-datasource-initialization: true
  #Cloudinary Properties
  #cloudinary:
  #api-key: 
  #api-secret: 
  #cloud-name: 
